### ISSUE TITLE
[HDRP] Gap between waves and underwater area.

### ISSUE THREAD

**Issue by Roland09** [wave-harmonic/crest#520]
There is a gap between the waves and the underwater area. 

It looks like this, see red arrow:

![gap](https://user-images.githubusercontent.com/10963432/82757186-0bd50880-9ddf-11ea-8cce-0ab22cabe6cd.jpg)

It doesn't happen all of the time, so there's no way to have the camera coordinates at a given position. However, I made a video, see below.

Reproduction steps:

* Unity 2019.3.14f1, HDRP 7.3.1, Crest HDRP 4.2 (Released: May 20, 2020) from the Asset Store
* install Crest HDRP
* open the threeboats demo scene
* dive under water, slightly below the surface so that you have both the waves and the underwater area visible
* move around with the camera

Here's a video, the bug starts to appear at around 00:16:

https://www.youtube.com/watch?v=lA8YE4BIYc8

**Comment by moosichu** [comment]
#526 Should resolve this issue, in the meantime you can set the horizon safety margin multiplier to 0 for now, although you might see some more flickering in the mean-time until the PR makes its way into the release.

**Comment by daleeidd** [comment]
4.3 is out with a fix for this. Please reopen if you still experience this issue

**Comment by Roland09** [comment]
The problem is still there in the current Asset Store version which is 4.4. Example screenshot:

![crest](https://user-images.githubusercontent.com/10963432/87873160-634abb80-c9bf-11ea-962b-db1ba44ddf73.png)

Reproduction:

* load the the threeboats demo scene
* set the camera to these coordinates

![cam](https://user-images.githubusercontent.com/10963432/87873184-adcc3800-c9bf-11ea-9fb3-bbe2ac03089d.png)

* hit play

**Comment by daleeidd** [comment]
Thanks. It does indeed appear to be still a problem. Since closing this issue, I have seen it appear in certain circumstances:
- with dynamic scaling
- turbulent water at certain positions when close to the surface and higher up on a wave

I was able to reproduce your case once where the safety margin didn't have an effect.

I'll reopen and will have to investigate further.

**Comment by daleeidd** [comment]
I believe that this time this issue will be solved with 4.5. *fingers crossed*

**Comment by daleeidd** [comment]
4.5 has been released. Be sure to let us know if you continue to see this problem.

**Comment by Roland09** [comment]
It's not gone unfortunately. It's better, but there's still a thin line:

![line](https://user-images.githubusercontent.com/10963432/90420427-3c63d000-e0b8-11ea-8558-604c59a81232.png)

**Comment by daleeidd** [comment]
What happens if you adjust the horizon safety multiplier on the underwater post process effect?

**Comment by daleeidd** [comment]
I had a look at earlier screenshots, and you might have it set to zero. If you try changing it back to the default (I think it is 0.01) it should solve it.

**Comment by Roland09** [comment]
Have to set it higher, i. e. around 0.26 it vanishes for me. Sounds a bit too high compared to 0.01. But for my situation it's fine.

**Comment by daleeidd** [comment]
Is this still the three boat scene and with those camera coordinates provided above? To reproduce, do you enter play mode with the time frozen?

**Comment by Roland09** [comment]
It's the boat scene with a custom boat in it. It happens while driving with the boat, I can look around the boat and underwater while driving with my modification. However, I just installed Crest HDRP into a new project and used the boat scene alone and it works without problems with a fly-cam. I'll try to create a reproduction case, I guess it's best to keep the ticket closed for now, must be something very specific to my settings. Thanks for your efforts!

**Comment by huwb** [comment]
Thanks for your help.

**Comment by daleeidd** [comment]
Hans on discord has reported that changing from 0.01f to 0.1 solved the problem.

**Comment by daleeidd** [comment]
@huwb Here is a scene which has a few reproducible issues which necessitated the safety margin. These have been solved by the safety margin. It requires the "feature/post-proc-underwater-2" branch. It has four cameras:

**ScreenVRes_896_NoWaves_BackFace**
Vertical resolution needs to be 896. Waves (nested under the ocean renderer) needs to be disabled. This isn't a horizon line issue, but looks like a back face issue.

**ScreenVRes_912_NoWaves_Line**
Vertical resolution needs to be 912. Waves need to be disabled. This is the original problem. Safety margin is set to zero.

**Waves_AboveHorizonLine**
Waves need to be enabled. This is an issue introduced by the safety margin. Safety margin is set to 1.0 which is much larger than the default to exhibit the issue.

**Waves_BelowHorizonLine**
Same as above.

[Underwater Horizon Issue.zip](https://github.com/crest-ocean/crest/files/5556834/Underwater.Horizon.Issue.zip)

I have been unable to reproduce the issue that others where increasing the safety margin apparently solves it.

**Comment by daleeidd** [comment]
@huwb made this a branch instead ([test/underwater-horizon-line-issue](https://github.com/crest-ocean/crest/tree/test/underwater-horizon-line-issue)). All you have to do now is switch between cameras using the C key. It should handle everything including setting the screen resolution.

**Comment by brucekirkpatrick** [comment]
Dale, while debugging this problem in my scene, I noticed that it could be helpful to try to include some adjustments for the camera vertical rotation, the field of view to make the HorizonSafetyMarginMultiplier value more accurate.   I'm using a wider field of view in a third person opsive ultimate character controller and it makes the problem much more noticeable compared to the first person view in the demo.  Also, you need to be fairly shallow in the water, like the height of a character (2 or 3) to see it.  If you go down much further, the artifacts go away because the mask math is only inaccurate near the surface.    I have my far clipping plane at 4000 which also helped because it was at 400 originally making the problem worse.    I am not able to understand how to compensate mathematically for the third person camera rotations and this mask which is mapped to screen space I guess.  It seems like I can just fudge the number higher dynamically in correlation to the field of view, but I'm not sure the formula.   I'll let you know if I find a solution, but otherwise, maybe you could revisit this.  Thanks!

**Comment by brucekirkpatrick** [comment]
Dale,

Dale,  I fixed this problem, and there is nothing wrong with Crest.  Debugging my scene further, I found there is an issue with Opsive Ultimate Character Controller causing the horizontal line problem.  If I enable First Person Transform Look camera type, while the Third Person Adventure is the active camera, it actually renders a double image.  When I change the field of view, this causes the horizontal line artifact, because I believe it is somehow rendering both cameras and the image is correct for both of them.  I wonder if any other developers using Opsive have this feature causing hidden double rendering.  When I remove that camera type, I am no longer able to break crest underwater with 0.01f HorizonSafetyMarginMultiplier.      The mysterious double rendering was tough for me to understand as a beginner because it was invisible when both cameras were the same field of view.   I'm sure this hurt performance rendering twice as well.  Just now, I saw there was a child camera enabled under Main Camera and it has its own independent settings.   I think you have fixed this horizontal line bug actually, but it is getting reintroduced due to other issues like Opsive UCC having a bug or configuration issues.  When I was debugging the crest code, I also output the field of view every frame and I noticed it was calling the function twice with 2 different field of view.  I didn't understand why until now.  It's hard to visualize weird rendering problems, when they are being compounded by other issues like this.  I've also had some weird z-fighting issues related to this before, because most of the time only one camera has the priority, but when I change the field of view, it really revealed what it was finally.    I guess people could be trying to render multiple cameras at once sometimes, but more likely a mistake in these beginner projects.  I reported this to Opsive on discord to verify if it is a bug or some kind of configuration issue.  I don't see a way to stop the double rendering in the editor other then removing the camera type.   It is a half baked idea perhaps.

**Comment by daleeidd** [comment]
@brucekirkpatrick Thank you for the update. We have had a few report this as an ongoing issue so I will keep it open. That is a good point that some of these issues might be caused by some other rendering feature which we aren't testing for.

**Comment by daleeidd** [comment]
@dkyeck provided a possible solution in #728 here: https://github.com/wave-harmonic/crest/issues/728#issue-788594249

**Comment by daleeidd** [comment]
I'll close since we haven't had many cases of this being an issue anymore other than edge cases which 4.13 should solve by moving horizon code from C# to HLSL.
