### ISSUE TITLE
ShapeFFT and ShapeGerstner produce lines in foam simulation data

### ISSUE THREAD

**Issue by daleeidd** [wave-harmonic/crest#878]
**Describe the bug**
Reported by @klauskobald on Discord. When using the ShapeFFT, foam simulation data appears to have grid lines.

**Screenshots / video**
![Evidence](https://cdn.discordapp.com/attachments/559872374682681345/867152697610469416/unknown.png)

**Versions**
Latest

**To Reproduce**
1. In the main scene, swap ShapeGerstnerBatched for ShapeFFT.
2. Reduce foam fade rate to something like 0.2 to make it more prominent.

**Platform**
 - Editor and Standalone
 - MacOS and Windows

**Additional context**
I tried disabling the variance to see if it was that but had no effect from what I could see.

**Comment by huwb** [comment]
Thanks for posting. I don't immediately know what works cause this but will post if I figure it out

**Comment by gamemachine** [comment]
This is not specific to fft, it happens with shape gerstner also.

**Comment by daleeidd** [comment]
It also affects ShapeGerstnerBatched, but it is not noticeable with a full spectrum.

@huwb I think ShapeGerstner and ShapeFFT are more susceptible because they are tiled? Rendering the Jacobian shows the issue still. The foam data from the ShapeGerstnerBatched appears more stable. An option could be to add noise or blur the foam data.

**Comment by huwb** [comment]
Would it be possible to see it happening for SGB? With a simplified spectrum would be useful.

**Comment by daleeidd** [comment]
Sure. Test branch here: https://github.com/wave-harmonic/crest/tree/test/foam-grid-issue

Test scenes are under Test folder. There is one scene per shape type.

**Comment by huwb** [comment]
Thanks. Weirdly i suddenly seem to repro it easily by just dropping in an FFT component.

It looks indeed like the wave patches are not tiling. I see lines every 0.5m which is exactly the size of the first wave cascade. If i turn off ~0.5m waves in the spectrum sliders, they go away.

I don't know why the waves are not tiling properly, the FFT was not messed with too much. so it is supposed to be strictly repeating patches (FFT is not able to do non-repeating). Might be worth comparing the spectrum with other similar code, or hacking the spectrum to only have one non-zero value to produce a single wave and try to show that it clearly does not tile.

Will post again if i make progress.

**Comment by daleeidd** [comment]
Fixed with 4.14.

**Comment by klauskobald** [comment]
Has this really been fixed?
I still get lines after updating from 4.13 - 4.15.
Do I need to replace components?

<img width="518" alt="image" src="https://user-images.githubusercontent.com/278428/165135631-452cf5ca-a3db-4e8f-a060-42822a4d7682.png">

**Comment by daleeidd** [comment]
> I still get lines after updating from 4.13 - 4.15. Do I need to replace components?

It should have been fixed in 4.14. Have you seen any improvement? It may still be possible to incur these with low settings perhaps.

**Comment by klauskobald** [comment]
Watch the image above. The foam damping was almost zero - just to illustrate. But one can also see it with other settings. The "idea" of stripes is everywhere. It has not changed at all compared to 4.13. What component(s) is producing that? What files are involved, so I could have a look at the diff.

**Comment by daleeidd** [comment]
#903 was the fix for ShapeFFT and #968 for ShapeGerstner. They increase the quality of the waves which reduces the repeating grid pattern. It didn't eliminate it completely. Maybe certain quality settings will make the pattern more prominent, but you should've seen an improvement.

**Comment by klauskobald** [comment]
I tried different values for SAMPLES_PER_WAVE (in FFTSpectrum & ShapeFFT) but cannot see any difference. It looks more or less like this.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/278428/165469224-a9448b5b-7059-4d0a-9a42-1a9dc1a0e0c8.png">

There is 4 WaterInteractionSpheres producing the waves with these parameters:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/278428/165472448-076ace07-50bf-42e5-ab86-094961238e33.png">
Greater weight produces more waves and more of the lines.

**Comment by daleeidd** [comment]
So the lines only appear because of the _Sphere Water Interaction_ and FFTs together? There is a resolution param on the ShapeFFT. Not sure if it will help with these sort of patterns.

**Comment by klauskobald** [comment]
The strips are everywhere. The WaterInteraction creates more waves, that´s why they are better visible. But here is the scene away from WaterInteraction. You can see the lines 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/278428/165727704-7bb39410-7909-4ab6-abd8-414ae12e6ee1.png">
Stripes align always on the x-axis, and it seems like they are only in the inner most LOD.
<img width="424" alt="image" src="https://user-images.githubusercontent.com/278428/165728169-b1e529bc-cd67-4414-9bb4-599a291e3a71.png">

**Comment by daleeidd** [comment]
Are you able to share a minimal scene or presets to reproduce? I haven't seen these lines that prominent since they were fixed. No need to provide Crest as I have a copy (I'll use latest URP version). Can send on Discord if you want.

**Comment by klauskobald** [comment]
This is an export of a prefab with minimal dependencies.
http://clients.kobald.com/crest/ocean/
I could not get it to work in a new project because of some urp setting. If you have a working scene it should be ok, I think.

**Comment by daleeidd** [comment]
Thanks! I can see them now. Looks like we only improved the situation for a OR resolution of 384. Anything appears to produces the pattern. I'll reopen.

**Comment by klauskobald** [comment]
That´s interesting - I can live with 384.
Question: a higher number (like 384) will use more cpu or gpu? If I increased _geometryDownSampleFactor to 4, would that compensate for higher cpu usage then?

**Comment by daleeidd** [comment]
Mostly GPU and memory. Increasing that will help performance but I don't think it will help with CPU.

**Comment by daleeidd** [comment]
Related: https://discord.com/channels/559866092546424832/985065764065267762
